config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "sessions#new"

  resources :users

  resources :bands do 
    resources :albums, only: [:new, :index]
  end

  resource :session
  resources :albums do
    resources :tracks, only: [:new, :index]
  end

  resources :tracks
end

app/models/album.rb
class Album < ApplicationRecord

    validates :title, presence: true
    validates :year, presence: true
    validates :album_type, inclusion: { in: ["Live", "Studio" ]}
    validates :album_type, presence: true
    validates :band_id, presence: true

    belongs_to :band
    has_many :tracks, dependent: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
    
    validates :name, presence: true

    has_many :albums, dependent: :destroy
    has_many :tracks, through: :albums

end

app/models/track.rb
class Track < ApplicationRecord

    validates :title, presence: true
    validates :track_number, presence: true

    belongs_to :album
    has_one :band, through: :album
end

app/models/user.rb
class User < ApplicationRecord
    attr_reader :password   
    
    validates :email, presence: true
    validates_uniqueness_of :email
    validates :password_digest, presence: {message: "Password can't be blank"}
    validates :password, length: { minimum: 6, allow_nil: true }
    validates :session_token, presence: true

    after_initialize :ensure_session_token

    has_many :bands, dependent: :destroy


    def generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= self.generate_session_token
    end

    def password= (password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end



    



  

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :authenticate_user!


    def index
        @albums = Album.all
        render :index
    end

    def edit
        @album = Album.find(params[:id])
        @band = Band.find_by(id: @album.band_id)
        render :edit
    end

    def update
        @album = Album.find(params[:id])
        @album.update(album_params)
        redirect_to album_path(@album)
    end

    def show
        @album = Album.find(params[:id])
        @tracks = @album.tracks
        @band = Band.find_by(id: @album.band_id)
        render :show
    end

    def new
        @band = Band.find_by(id: params[:band_id])
        @album = Album.new(band_id: params[:band_id])
        render :new
    end

    def create
        @album = Album.new(album_params)
        if @album.valid?
            puts @album.errors.full_messages
            @album.save
            flash[:success] = "Album created"
            redirect_to album_path(@album)
        else
            puts @album.errors.full_messages
            flash.now[:alert] = "#{@album.errors.full_messages.to_sentence}"
            render :new
        end

    end 

    def destroy
        album = Album.find(params[:id])
        album.destroy
        redirect_to albums_path
    end

    private
        def album_params
            params.require(:album).permit(:title, :year, :band_id, :album_type, :created_at, :updated_at)
        end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?


    def login!(user)
        @current_user = user
        session[:session_token] = user.session_token
    end

    def logout!
        current_user.try(:reset_session_token)
        session[:session_token] = nil
    end

    def current_user
        return nil if session[:session_token].nil?
        @current_user ||= User.find_by(session_token: session[:session_token])
    end


    private

        def authenticate_user!
            redirect_to :root unless !current_user.nil?
        end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
    before_action :authenticate_user!


    def index
        @bands = Band.all
    end


    def new 
        @band = Band.new
    end

    def create
        @band = Band.new(band_params)
        if @band.valid?
            @band.save
            redirect_to band_path(@band)
        else
            flash.now[:error] = "Please ensure all fields are filled out."
            render new_band_path
        end
    end

    def edit
        @band = Band.find_by(id: params[:id])
    end

    def update
        @band = Band.find_by(id: params[:id])
        if @band.update_attributes(band_params)
            flash[:success] = "Band Updated!"
            redirect_to bands_path
        else
            flash[:alert] = "Something went wrong..."
            render edit_band_path
        end

    end

    def show
        @band = Band.find_by(id: params[:id])
    end

    def destroy
        @band = Band.find_by(id: params[:id])
        @band.destroy
    end

    private
         
        def band_params
            params.permit(:name)
        end

        def authenticate
            if current_user.nil?
                flash[:alert] = "You must be logged in to perform that action."
                redirect_to new_session_path
            end
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        render new_session_path
    end

    def create
        user = User.find_by_credentials(
            params[:user][:email],
            params[:user][:password]
        )

        if user.nil?
            flash[:error] = "Email / password is incorrect or that user does not exist."
            redirect_to new_session_path
        else
            login!(user)
            flash[:success] = "Welcome back #{user.email}"
            redirect_to user_path(user)
        end
    end

    def destroy
        logout!
        flash[:success] = "You have been logged out!"
        redirect_to new_session_url
    end



end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    before_action :authenticate_user!


    def new
        @album = Album.find_by(id: params[:album_id])
        @band_albums = Album.where(band_id: @album.band_id)
        @track = Track.new(album_id: params[:album_id])
    end

    def create
        @album = Album.find_by(id: track_params[:album_id])
        @track = Track.new(track_params)
        if @track.valid?
            @track.save
            redirect_to album_path(@album)
        else
            flash.now[:error] = @track.errors.full_messages.to_sentence
            render 'new'
        end
    end

    def show
        @track = Track.find_by(id: params[:id])
        @album = Album.find_by(id: @track.album_id)
        render 'show' 
    end

    def edit
        @track = Track.find_by(id: params[:id])
        @album = Album.find_by(id: @track.album_id)
        @band_albums = Album.where(band_id: @album.band_id)
        render 'edit'
    end

    def update
        @album = Album.find_by(id: params[:album_id])
        @track = Track.update(track_params)
        redirect_to album_path(@album)
    end

    def destroy
        @album = Album.find_by(id: params[:album_id])
        track = Track.find_by(id: params[:id])
        track.destroy
        redirect_to album_path(@album)
    end

    private 
        def track_params
            params.require(:track).permit(:title, :track_number, :lyrics, :album_id, :track_type)
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render new_user_path
    end


    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_path(@user)
        else
            flash[:error] = @user.errors.full_messages.to_sentence
            render new_user_path
        end
        
    end

    def index
    end

    def show
        @user = current_user
    end

    private

        def user_params
            params.require(:user).permit(:email, :password)
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%=  form_for @album do |f| %>

    <%= f.label :title, "Album Title" %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :year, "Album Year: " %>
    <%= f.text_field :year %>
    <br>
    <%= f.label :band_id, "Band: " %>
    <%= f.select :band_id, Band.all.map { |band| [ band.name, band.id ] }, prompt: "Select a Band", selected: "#{@band.try(:id)}" %>
    <br>
    <%= f.label :album_type, "Album Type: " %>

    <%= f.radio_button :album_type, "Studio" %>
    <%= f.label :album_type, "Studio", value: "Studio"%>
    
    <%= f.radio_button :album_type, "Live" %>
    <%= f.label :album_type, "Live", value: "Live"%>
    
    <br>
    <%= f.submit "Add Album"%>

<% end %>

app/views/albums/edit.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2> Edit <%= @album.title %> </h2>
        </div>
        <div class="card-body">
            <%= render 'form' %>
            <%= button_to "Back to Album", album_path(@album), method: :get, class: "btn btn-sm btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/albums/index.html.erb
<h2>  All Albums 
    <% unless @band.nil? %>
        <%= by @band.name %>
    <% end %> </h2>

<% @albums.each do |album| %>
<ul>
    <li> <%= link_to "#{album.title}", album_path(album) %>  </li>
</ul>
<% end %>

<%=  button_to "Bands Page", bands_path, method: :get %>

app/views/albums/new.html.erb
<h2>Add an Album </h2>
<%= render 'form' %>

app/views/albums/show.html.erb
<br>
<div class="container">
<div class="card">
    <div class="card-header">
        <h2>Album page for <%= @album.title %></h2>
    </div>

        <div class="card-body">
            <h3>Band: <%= @band.name %> </h3>
            <h3>Release Year: <%= @album.year %></h3>
            <h3>Album Type: <%= @album.album_type %>  </h3>
            <br>
            <div class="card">
                <div class="card-header">
                    <h2>  Tracks: </h2>
                </div>
                <div class="card-body">
                        <% @tracks.each do |track| %>
                            <ul>
                                <li><%= link_to "#{track.title}", track_path(track) %></li>
                            </ul>
                        <% end %>
                </div>
            </div>
            <br>
            <%= button_to "Add Track", new_album_track_path(@album), method: :get, class: "btn btn-sm btn-outline-secondary" %>
            <br>
            <%= button_to "All Albums", albums_path, method: :get, class: "btn btn-sm btn-outline-secondary" %>
            <br>
            <%= button_to "Back to Band Page", band_path(@band), method: :get, class: "btn btn-sm btn-outline-secondary" %>
            <br>
            <%= button_to "Delete", album_path(@album), method: :delete, class: "btn btn-sm btn-outline-secondary", data: { confirm: "Are you sure you want to delete this?" } %>
            <br>
            <%= button_to "Edit", edit_album_path(@album), method: :get, class: "btn btn-sm btn-outline-secondary" %>
        </div>
    </div>
</div>

app/views/bands/edit.html.erb
<h2>Edit Band</h2>

    <%= form_for @band do %>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= label_tag :name, "Band name" %>
        <%= text_field_tag :name %>
        <%= submit_tag "Update Band" %>
    <% end %>

app/views/bands/index.html.erb
<br>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>All the bands!</h2>
        </div>

        <div class="card-body">
            <ul>
                <% @bands.each do |band| %>
                    <li><%=link_to "#{band.name}", band_path(band) %></li>
                <% end %>
            </ul>


            <%= button_to "My Profile", user_path(current_user), method: :get %>
            <br>
            <%= button_to "Add a Band", new_band_path, method: :get %>
        </div>
    </div>

</div>

app/views/bands/new.html.erb
<br>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>Create a Band!</h2>
        </div>

        <div class="card-body">
            <div class="container">
                <%= form_for @band do %>
                    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                    <%= label_tag :name, "Band name" %>
                    <br>
                    <%= text_field_tag :name  %>
                    <br>
                    <br>
                    <%= submit_tag "Create Band", class: "btn btn-sm btn-outline-secondary" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/bands/show.html.erb
<br>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>Welcome to the page for <%= @band.name %></h2>
        </div>
        <div class="container">
        <br>
            <h3> Albums </h3>
            <ul>
                <% if @band.albums.empty? %>
                    <li><p>No Albums yet! But you can add one!</p></li>
                <% else %>
                    <% @band.albums.each do |album| %>
                        <li><%= link_to "#{album.title}", album_path(album) %></li>
                    <% end %>
                <% end %>
            </ul>

            <%= button_to "Return to all Bands", bands_path, method: :get, class: "btn btn-sm btn-outline-secondary" %>
            <br>
            <%= button_to "Add an Album", new_band_album_path(@band), method: :get, class: "btn btn-sm btn-outline-secondary" %>
            <br>    
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
         <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="collapse navbar-collapse" id="navbarNav">
            <a class="navbar-brand" href="<%= page_path('home')%>">Musiq</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            
              <div class="container">
                <ul class="navbar-nav">
                  <li class="nav-item active">
                    <a class="nav-link" href=" <%= page_path("home")%> ">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href=" <%= page_path("about") %> ">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="<%= new_session_path %>">Login</a>
                  </li>
                   <li class="nav-item">
                    <a class="nav-link" href="<%= new_user_path %>">Signup</a>
                  </li>
                </ul>
              </div>  
            </div>

            <div class="d-flex justify-content-end align-items-center">
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <% if !current_user.nil? %>
                <li class="nav-link disabled">Logged in as:</li> 
                <%= link_to "#{current_user.email}", user_path(current_user), class: "nav-link" %>
                
                <li class="d-flex nav-item align-items-center">
                  <form action="<%= session_url %>" method="POST">
                    <input type="hidden"
                          name="authenticity_token"
                          value="<%= form_authenticity_token %>">
                    <input type="hidden" value="delete" name="_method" />
                    <input class="btn btn-secondary btn-sm" type="submit" value="Logout" />
                  </form>
                </li>
                <% end %>
              </ul>
            </div>
            </div>
          </nav>
        
    <%= yield %>
  </body>
</html>

app/views/pages/_navbar.html.erb
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Musiq</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>

app/views/session/new.html.erb
<div class="d-flex container justify-content-center">
  <form action="/session" method="POST" class="d-flex form-signin align-items-center">
  <div class="container">
  <div class="row justify-content-center">
    <h1 class="h3 mb-4 font-weight-normal text-align-center">Musiq</h1>
  </div>
   <h5 class="font-weight-normal text-align-center">Log In</h5>
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">

    <label for="user_email">Email</label>
    <input type="text" name="user[email]" id="user_email" class='form-control'>

    <br />

    <label for="user_password">Password</label>
    <input type="password" name="user[password]" id="user_password" class="form-control">

    <br />

    <input type="submit" value="Log in" class="btn btn-sm btn-outline-secondary">
    
  </form>
  <br>
  <br>
  <%= button_to "Sign up", new_user_path, method: :get, class: "btn btn-sm btn-outline-secondary"%>
  </div>
</div>

app/views/tracks/_form.html.erb
<%= form_for @track do |f| %>

    <%= f.label :title, "Track Title" %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :track_number, "Track Number: " %>
    <%= f.select :track_number, (0..99).to_a %>
    <br>
    <%= f.label :albbum_id, "Album: " %>
    <%= f.select :album_id, @band_albums.map { |album| [ album.title, album.id ] }, prompt: "Select an Album", selected: "#{@album.try(:id)}" %>
    <br>
    <%= f.label :track_type, "Track Type: " %>

    <%= f.radio_button :track_type, "Regular" %>
    <%= f.label :track_type, "Regular", value: "Regular"%>
    
    <%= f.radio_button :track_type, "Bonus" %>
    <%= f.label :track_type, "Bonus", value: "Bonus"%>
    <br>
    <%= f.label :lyrcis, "Lyrics (Optional): " %>
    <br>
    <%= f.text_area :lyrics, cols: 20, rows: 20 %>

    <br>
    <%= f.submit "Submit Track", class: "btn btn-sm btn-outline-secondary"%>
<% end %>

app/views/tracks/edit.html.erb
<br>
<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>Edit <%= @track.title %> </h2>
        </div>
        <div class="card-body">
            <%= render 'form' %>
            <br>
            <%= button_to "Back to Track", track_path(@track), method: :get, class: "btn btn-sm btn-outline-secondary"%>
        </div>
    </div>
</div>

app/views/tracks/new.html.erb
<h3>  Add tracks to <%= @album.title %> </h3>
<%= render 'form' %>
<%= button_to "Back to Tracks", album_path(@album), method: :get %>

app/views/tracks/show.html.erb
<br>  
<div class="container">
  <div class="card">
    <div class="card-header">
      <h3>  Track info for <%= @track.title %></h3>
    </div>
    <div class="card-body">
      <p> Album: <%= @album.title %> </p>
      <p> Track Number: <%= @track.track_number %> </p>
      <% unless @track.lyrics.nil? %>
        <p> Lyrics: <%= @track.lyrics %> </p>
      <% end %>
      <br>
      <%= button_to "Back to Album", album_path(@album), method: :get, class: "btn btn-sm btn-outline-secondary" %>
      <br>
      <%= button_to "Delete", track_path(@track), method: :delete, class: "btn btn-sm btn-outline-secondary", data: { confirm: "Are you sure you want to delete this?" } %>
      <br>
      <%= button_to "Edit Track", edit_track_path(@track), method: :get, class: "btn btn-sm btn-outline-secondary" %>
    </div>
  </div>
</div>

app/views/user/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>Create User</h1>

<%= render "form", user: @user %>

<!-- app/views/users/_form.html.erb -->
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "patch" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_email"
     name="user[email]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->  

<% action = (@user.persisted? ? user_url(@user) : users_url) %>
<% method = (@user.persisted? ? "patch" : "post") %>
<% message = (@user.persisted? ? "Update Account" : "Create Account") %>

<div class="d-flex container justify-content-center">
   <form action="<%= action %>" method="post" class="d-flex form-signin align-items-center">
   <div class="container">
      <div class="row justify-content-center">
      <h1 class="h3 mb-4 font-weight-normal text-align-center">Musiq</h1>
      </div>
      <h5 class="font-weight-normal text-align-center">Sign Up</h5>
      <br>
      <input
         name="_method"
         type="hidden"
         value="<%= method %>">
      <input
         name="authenticity_token"
         type="hidden"
         value="<%= form_authenticity_token %>">

      <label for="user_email">Email</label>
      <input
         id="user_email"
         name="user[email]"
         type="text"
         class="form-control"
         >
      <br>

      <label for="user_password">Password</label>
      <input
         id="user_password"
         name="user[password]"
         type="password"
         class="form-control"
         >
      <br>

      <input type="submit" class="btn btn-sm btn-outline-secondary btn-outline" value="<%= message %>">
      </div>
   </form>
</div>

app/views/users/show.html.erb
<div class="container">
    <br>

    <div class="card">
        <h2 class="card-header"><%= @user.email %></h2>
        <br>
        <div class="container">
        <p>Hello User!</p>
        <%= button_to "Create a band", new_band_path, method: :get %>
        <br>
        <%= button_to "View Bands", bands_path, method: :get %>
        </div>
        <br>
    </div>

</div>